name: Horusec Scan

on: [push]

jobs:
  checking_code:
    runs-on: ubuntu-latest
    name: Horusec Scan
    steps:
      - name: Checkout 
        uses: actions/checkout@v2.3.4
      - name: Run Horusec
        id: run_horusec
        uses: fike/horusec-action@main
        with:
          arguments: "-c=horusec-config.json -p ./ -e=false"
      - name: Log Horusec output
        run: echo "${{ steps.run_horusec.outputs.stdout }}"
      - name: Create Issue
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: vulnerabilities } = JSON.parse('${{ steps.run_horusec.outputs.stdout }}');
            const title = 'Horusec Scan - Vulnerabilities Found';
            const body = ` **Vulnerabilities Found:** \`\`\` ${JSON.stringify(vulnerabilities, null, 2)} \`\`\`

            const { owner, repo } = context.repo;
            const newIssue = await github.rest.issues.create({
              owner: owner,
              repo: repo,
              title: title,
              body: body
            });
