name: Horusec Scan

on: [push]

jobs:
  checking_code:
    runs-on: ubuntu-latest
    name: Horusec Scan
    steps:
      - name: Checkout 
        uses: actions/checkout@v2.3.4
      - name: Run Horusec
        id: run_horusec
        uses: fike/horusec-action@main
        with:
          arguments: "-c=horusec-config.json -p ./ -e=false"
      - name: Check for Vulnerabilities
        run: |
          if grep -q "Vulnerabilities found" ${{ steps.run_horusec.outputs.stdout }}; then
            echo "Vulnerabilities found, creating an issue..."
            # Você pode adicionar aqui um script ou comando para criar uma issue.
            # Por exemplo, você pode usar a API do GitHub para criar uma issue usando curl.
            # Certifique-se de configurar as credenciais de autenticação adequadamente para criar a issue.
          else
            echo "No vulnerabilities found."
          fi
