on: [push]

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run script
        uses: actions/github-script@v6
        with:
          script: |
            try {
              const output = ''; // Substitua pelo valor correto da saída
              const { data: vulnerabilities } = JSON.parse(output);
              const title = 'Horusec Scan - Vulnerabilities Found';
              const body = `**Vulnerabilities Found:** \n\`\`\` ${JSON.stringify(vulnerabilities, null, 2)} \`\`\``;

              const { owner, repo } = context.repo;
              const newIssue = await github.rest.issues.create({
                owner: owner,
                repo: repo,
                title: title,
                body: body
              });

              console.log('Nova issue criada:', newIssue);
            } catch (error) {
              console.error('Erro ao fazer o parse do JSON:', error);
            }
