name: horusec

on:
  push:
    branches:
      - main  # Adjust to your repository's default branch

jobs:
  horusec-analysis:
    runs-on: ubuntu-latest  # You can choose the runner environment you prefer

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Horusec analysis
        uses: docker://fike/horusec-action:v0.2.2
        with:
          arguments: --config-file-path=horusec-config.json
