name: SecurityPipeline

on: [push]

jobs:
  horusec-security:
    name: horusec-security
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get remove containerd.io
        sudo apt-get -y install docker.io
        sudo dpkg --configure -a
        sudo apt-get install -f
        sudo systemctl start docker
        sudo systemctl enable docker
    - name: Running Horusec Security
      run: |
        curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
        horusec start -p="./"

