name: OWASP ZAP Cron Job
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  dast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2
      - name: Executar OWASP ZAP
        uses: zaproxy/action-baseline@v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://flask-restplus-example-server.herokuapp.com/api/v1/' # URL do seu site ou ip
          cmd_options: '-a'
